require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe IncidenciaController do

  # This should return the minimal set of attributes required to create a valid
  # Incidencium. As you add validations to Incidencium, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "nombre" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # IncidenciaController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all incidencia as @incidencia" do
      incidencium = Incidencium.create! valid_attributes
      get :index, {}, valid_session
      assigns(:incidencia).should eq([incidencium])
    end
  end

  describe "GET show" do
    it "assigns the requested incidencium as @incidencium" do
      incidencium = Incidencium.create! valid_attributes
      get :show, {:id => incidencium.to_param}, valid_session
      assigns(:incidencium).should eq(incidencium)
    end
  end

  describe "GET new" do
    it "assigns a new incidencium as @incidencium" do
      get :new, {}, valid_session
      assigns(:incidencium).should be_a_new(Incidencium)
    end
  end

  describe "GET edit" do
    it "assigns the requested incidencium as @incidencium" do
      incidencium = Incidencium.create! valid_attributes
      get :edit, {:id => incidencium.to_param}, valid_session
      assigns(:incidencium).should eq(incidencium)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Incidencium" do
        expect {
          post :create, {:incidencium => valid_attributes}, valid_session
        }.to change(Incidencium, :count).by(1)
      end

      it "assigns a newly created incidencium as @incidencium" do
        post :create, {:incidencium => valid_attributes}, valid_session
        assigns(:incidencium).should be_a(Incidencium)
        assigns(:incidencium).should be_persisted
      end

      it "redirects to the created incidencium" do
        post :create, {:incidencium => valid_attributes}, valid_session
        response.should redirect_to(Incidencium.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved incidencium as @incidencium" do
        # Trigger the behavior that occurs when invalid params are submitted
        Incidencium.any_instance.stub(:save).and_return(false)
        post :create, {:incidencium => { "nombre" => "invalid value" }}, valid_session
        assigns(:incidencium).should be_a_new(Incidencium)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Incidencium.any_instance.stub(:save).and_return(false)
        post :create, {:incidencium => { "nombre" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested incidencium" do
        incidencium = Incidencium.create! valid_attributes
        # Assuming there are no other incidencia in the database, this
        # specifies that the Incidencium created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Incidencium.any_instance.should_receive(:update).with({ "nombre" => "MyString" })
        put :update, {:id => incidencium.to_param, :incidencium => { "nombre" => "MyString" }}, valid_session
      end

      it "assigns the requested incidencium as @incidencium" do
        incidencium = Incidencium.create! valid_attributes
        put :update, {:id => incidencium.to_param, :incidencium => valid_attributes}, valid_session
        assigns(:incidencium).should eq(incidencium)
      end

      it "redirects to the incidencium" do
        incidencium = Incidencium.create! valid_attributes
        put :update, {:id => incidencium.to_param, :incidencium => valid_attributes}, valid_session
        response.should redirect_to(incidencium)
      end
    end

    describe "with invalid params" do
      it "assigns the incidencium as @incidencium" do
        incidencium = Incidencium.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Incidencium.any_instance.stub(:save).and_return(false)
        put :update, {:id => incidencium.to_param, :incidencium => { "nombre" => "invalid value" }}, valid_session
        assigns(:incidencium).should eq(incidencium)
      end

      it "re-renders the 'edit' template" do
        incidencium = Incidencium.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Incidencium.any_instance.stub(:save).and_return(false)
        put :update, {:id => incidencium.to_param, :incidencium => { "nombre" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested incidencium" do
      incidencium = Incidencium.create! valid_attributes
      expect {
        delete :destroy, {:id => incidencium.to_param}, valid_session
      }.to change(Incidencium, :count).by(-1)
    end

    it "redirects to the incidencia list" do
      incidencium = Incidencium.create! valid_attributes
      delete :destroy, {:id => incidencium.to_param}, valid_session
      response.should redirect_to(incidencia_url)
    end
  end

end
