require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe LecturistasController do

  # This should return the minimal set of attributes required to create a valid
  # Lecturista. As you add validations to Lecturista, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "nombre" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # LecturistasController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all lecturistas as @lecturistas" do
      lecturista = Lecturista.create! valid_attributes
      get :index, {}, valid_session
      assigns(:lecturistas).should eq([lecturista])
    end
  end

  describe "GET show" do
    it "assigns the requested lecturista as @lecturista" do
      lecturista = Lecturista.create! valid_attributes
      get :show, {:id => lecturista.to_param}, valid_session
      assigns(:lecturista).should eq(lecturista)
    end
  end

  describe "GET new" do
    it "assigns a new lecturista as @lecturista" do
      get :new, {}, valid_session
      assigns(:lecturista).should be_a_new(Lecturista)
    end
  end

  describe "GET edit" do
    it "assigns the requested lecturista as @lecturista" do
      lecturista = Lecturista.create! valid_attributes
      get :edit, {:id => lecturista.to_param}, valid_session
      assigns(:lecturista).should eq(lecturista)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Lecturista" do
        expect {
          post :create, {:lecturista => valid_attributes}, valid_session
        }.to change(Lecturista, :count).by(1)
      end

      it "assigns a newly created lecturista as @lecturista" do
        post :create, {:lecturista => valid_attributes}, valid_session
        assigns(:lecturista).should be_a(Lecturista)
        assigns(:lecturista).should be_persisted
      end

      it "redirects to the created lecturista" do
        post :create, {:lecturista => valid_attributes}, valid_session
        response.should redirect_to(Lecturista.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved lecturista as @lecturista" do
        # Trigger the behavior that occurs when invalid params are submitted
        Lecturista.any_instance.stub(:save).and_return(false)
        post :create, {:lecturista => { "nombre" => "invalid value" }}, valid_session
        assigns(:lecturista).should be_a_new(Lecturista)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Lecturista.any_instance.stub(:save).and_return(false)
        post :create, {:lecturista => { "nombre" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested lecturista" do
        lecturista = Lecturista.create! valid_attributes
        # Assuming there are no other lecturistas in the database, this
        # specifies that the Lecturista created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Lecturista.any_instance.should_receive(:update).with({ "nombre" => "MyString" })
        put :update, {:id => lecturista.to_param, :lecturista => { "nombre" => "MyString" }}, valid_session
      end

      it "assigns the requested lecturista as @lecturista" do
        lecturista = Lecturista.create! valid_attributes
        put :update, {:id => lecturista.to_param, :lecturista => valid_attributes}, valid_session
        assigns(:lecturista).should eq(lecturista)
      end

      it "redirects to the lecturista" do
        lecturista = Lecturista.create! valid_attributes
        put :update, {:id => lecturista.to_param, :lecturista => valid_attributes}, valid_session
        response.should redirect_to(lecturista)
      end
    end

    describe "with invalid params" do
      it "assigns the lecturista as @lecturista" do
        lecturista = Lecturista.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Lecturista.any_instance.stub(:save).and_return(false)
        put :update, {:id => lecturista.to_param, :lecturista => { "nombre" => "invalid value" }}, valid_session
        assigns(:lecturista).should eq(lecturista)
      end

      it "re-renders the 'edit' template" do
        lecturista = Lecturista.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Lecturista.any_instance.stub(:save).and_return(false)
        put :update, {:id => lecturista.to_param, :lecturista => { "nombre" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested lecturista" do
      lecturista = Lecturista.create! valid_attributes
      expect {
        delete :destroy, {:id => lecturista.to_param}, valid_session
      }.to change(Lecturista, :count).by(-1)
    end

    it "redirects to the lecturistas list" do
      lecturista = Lecturista.create! valid_attributes
      delete :destroy, {:id => lecturista.to_param}, valid_session
      response.should redirect_to(lecturistas_url)
    end
  end

end
