require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MedidorsController do

  # This should return the minimal set of attributes required to create a valid
  # Medidor. As you add validations to Medidor, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "idactivo" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MedidorsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all medidors as @medidors" do
      medidor = Medidor.create! valid_attributes
      get :index, {}, valid_session
      assigns(:medidors).should eq([medidor])
    end
  end

  describe "GET show" do
    it "assigns the requested medidor as @medidor" do
      medidor = Medidor.create! valid_attributes
      get :show, {:id => medidor.to_param}, valid_session
      assigns(:medidor).should eq(medidor)
    end
  end

  describe "GET new" do
    it "assigns a new medidor as @medidor" do
      get :new, {}, valid_session
      assigns(:medidor).should be_a_new(Medidor)
    end
  end

  describe "GET edit" do
    it "assigns the requested medidor as @medidor" do
      medidor = Medidor.create! valid_attributes
      get :edit, {:id => medidor.to_param}, valid_session
      assigns(:medidor).should eq(medidor)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Medidor" do
        expect {
          post :create, {:medidor => valid_attributes}, valid_session
        }.to change(Medidor, :count).by(1)
      end

      it "assigns a newly created medidor as @medidor" do
        post :create, {:medidor => valid_attributes}, valid_session
        assigns(:medidor).should be_a(Medidor)
        assigns(:medidor).should be_persisted
      end

      it "redirects to the created medidor" do
        post :create, {:medidor => valid_attributes}, valid_session
        response.should redirect_to(Medidor.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved medidor as @medidor" do
        # Trigger the behavior that occurs when invalid params are submitted
        Medidor.any_instance.stub(:save).and_return(false)
        post :create, {:medidor => { "idactivo" => "invalid value" }}, valid_session
        assigns(:medidor).should be_a_new(Medidor)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Medidor.any_instance.stub(:save).and_return(false)
        post :create, {:medidor => { "idactivo" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested medidor" do
        medidor = Medidor.create! valid_attributes
        # Assuming there are no other medidors in the database, this
        # specifies that the Medidor created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Medidor.any_instance.should_receive(:update).with({ "idactivo" => "" })
        put :update, {:id => medidor.to_param, :medidor => { "idactivo" => "" }}, valid_session
      end

      it "assigns the requested medidor as @medidor" do
        medidor = Medidor.create! valid_attributes
        put :update, {:id => medidor.to_param, :medidor => valid_attributes}, valid_session
        assigns(:medidor).should eq(medidor)
      end

      it "redirects to the medidor" do
        medidor = Medidor.create! valid_attributes
        put :update, {:id => medidor.to_param, :medidor => valid_attributes}, valid_session
        response.should redirect_to(medidor)
      end
    end

    describe "with invalid params" do
      it "assigns the medidor as @medidor" do
        medidor = Medidor.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Medidor.any_instance.stub(:save).and_return(false)
        put :update, {:id => medidor.to_param, :medidor => { "idactivo" => "invalid value" }}, valid_session
        assigns(:medidor).should eq(medidor)
      end

      it "re-renders the 'edit' template" do
        medidor = Medidor.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Medidor.any_instance.stub(:save).and_return(false)
        put :update, {:id => medidor.to_param, :medidor => { "idactivo" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested medidor" do
      medidor = Medidor.create! valid_attributes
      expect {
        delete :destroy, {:id => medidor.to_param}, valid_session
      }.to change(Medidor, :count).by(-1)
    end

    it "redirects to the medidors list" do
      medidor = Medidor.create! valid_attributes
      delete :destroy, {:id => medidor.to_param}, valid_session
      response.should redirect_to(medidors_url)
    end
  end

end
